{% set name = "napari-nd2-folder-viewer" %}
{% set version = "0.0.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-nd2-folder-viewer-{{ version }}.tar.gz
  sha256: c43de65a1981ab1382366aeb5bb1415d1c735e40bf235ab5a681303b5dddcc7b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - dask-core
    - desert
    - julian
    - magicgui
    - marshmallow
    - napari
    - napari-animation
    - nd2
    - numpy
    - openpyxl
    - pandas
    - python >={{ python_min }}
    - pyyaml
    - qtpy
    - scikit-learn

test:
  imports:
    - napari_nd2_folder_viewer
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/gatoniel/napari-nd2-folder-viewer
  summary: Look through separate nd2 files in one viewer.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
